### ISSUE TITLE
readme.md wakatime link

### ISSUE THREAD

**Issue by mondychan** [ChocolateApp/Chocolate#13]
`[![wakatime](https://wakatime.com/badge/user/4cf4132a-4ced-411d-b714-67bdbdc84527/project/ecce3f45-dba9-4e4b-8f78-693c6d237d1c.svg)](https://wakatime.com/badge/user/4cf4132a-4ced-411d-b714-67bdbdc84527/project/ecce3f45-dba9-4e4b-8f78-693c6d237d1c)`

link for wakatime in readme.md doesnt work
redirects to a page
```
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Comment by Impre-visible** [comment]
You right, I will remove the not used link, thanks
