### ISSUE TITLE
possible code duplication (classes)

### ISSUE THREAD

**Issue by clach04** [ChocolateApp/Chocolate#3]
app.py and intro.py appear to duplicate code, for example:

* https://github.com/ChocolateApp/Chocolate/blob/9d84946c67b9e2423350548638277ce2084ffd3c/intro.py#L39
* https://github.com/ChocolateApp/Chocolate/blob/9d84946c67b9e2423350548638277ce2084ffd3c/app.py#L106

**Comment by clach04** [comment]
$ rg "class " intro.py app.py
    app.py
    61:class Users(db.Model, UserMixin):
    85:class Movies(db.Model):
    126:class Series(db.Model):
    164:class Seasons(db.Model):
    192:class Episodes(db.Model):
    219:class Games(db.Model):
    249:class OthersVideos(db.Model):
    272:class Language(db.Model):
    281:class Actors(db.Model):
    302:class Libraries(db.Model):
    808:class EpisodeGroup():

    intro.py
    30:class Libraries(db.Model):
    47:class Series(db.Model):
    85:class Seasons(db.Model):
    113:class Episodes(db.Model):

**Comment by Impre-visible** [comment]
Actually intro.py is in WIP, it's not planned to be used for the actual version

**Comment by Impre-visible** [comment]
In the next version I'm gonna remove that 👍🏻
