### ISSUE TITLE
Missing source code install.sh

### ISSUE THREAD

**Issue by clach04** [ChocolateApp/Chocolate#4]
https://github.com/ChocolateApp/Chocolate/blob/9d84946c67b9e2423350548638277ce2084ffd3c/README.md?plain=1#L47 mentions install.sh, there is one for download in https://github.com/ChocolateApp/Chocolate/releases/tag/v5.6.0 but I can not locate the source code in the repository.

**Comment by Impre-visible** [comment]
The source code is in another rep, i wil combine them

**Comment by Impre-visible** [comment]
I just published chocolate on pypi, so an installation script is not needed anymore
